export const ADD_TEACHER_REQUEST = "ADD_TEACHER_REQUEST";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const ADD_TEACHER_FAILURE = "ADD_TEACHER_FAILURE";

export const GET_TEACHERS_REQUEST = "GET_TEACHERS_REQUEST";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_FAILURE = "GET_TEACHERS_FAILURE";

export const DELETE_TEACHER_REQUEST = "DELETE_TEACHER_REQUEST";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAILURE = "DELETE_TEACHER_FAILURE";

export const CHANGE_QUERIES = "CHANGE_QUERIES";

export const FIND_TEACHER_REQUEST = "FIND_TEACHER_REQUEST";
export const FIND_TEACHER_SUCCESS = "FIND_TEACHER_SUCCESS";
export const FIND_TEACHER_FAILURE = "FIND_TEACHER_FAILURE";
